[theme]
primaryColor = "#2DD4BF"
backgroundColor = "#0B1220"
secondaryBackgroundColor = "#111827"
textColor = "#F8FAFC"
font = "sans serif"

[server]
runOnSave = true

[browser]
gatherUsageStats = false